version: '3.8'
services:
  nbd_api_dev:
    user: tb5
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nbd-api-dev
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - /home/tb5/harmony_constant/NEO:/water_level
