server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: false
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.151.2.62)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=10.151.2.62)(PORT=1521))(LOAD_BALANCE=true)(FAILOVER=true)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=kttv_warehouse)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC))))
    username: kttv
    password: kttv#123@
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 20000       #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 1                 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 300            #maximum pool size
      idle-timeout: 10000             #maximum idle time for connection
      max-lifetime: 2000              # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      pool-name: NBD_API
      data-source-properties:
        v$session.program=NBD_API
casbin:
  enableCasbin: true
  useSyncedEnforcer: false
  autoSave: true
  storeType: jdbc
  initializeSchema: create
  model: classpath:casbin/model.conf
  useDefaultModelIfModelNotSetting: true
  enableWatcher: false
logging:
  config: classpath:logback.xml
sysId: 1
water:
  level:
    file:
      out: /water_level/



