
casbin:
  enableCasbin: true
  useSyncedEnforcer: false
  autoSave: true
  storeType: jdbc
  initializeSchema: create
  model: classpath:casbin/model.conf
  useDefaultModelIfModelNotSetting: true
  enableWatcher: false
logging:
  config: classpath:logback.xml